numero1=int(input("digite o primeiro numero"))
numero2=int(input("digite o segundo numero"))
numero3=int(input("digite o segundo numero"))
numero4=int(input("digite o segundo numero"))
print(numero1 + numero2 + numero3 + numero4)